stages:
  - build

build-job:
  image: $CI_REGISTRY/jkridner/debian-build
  tags: ["docker-amd64"]
  stage: build
  before_script:
    - wget https://dr-download.ti.com/software-development/ide-configuration-compiler-or-debugger/MD-ayxs93eZNN/3.2.2.LTS/ti_cgt_armllvm_3.2.2.LTS_linux-x64_installer.bin
    - chmod +x ./ti_cgt_armllvm_3.2.2.LTS_linux-x64_installer.bin
    - ./ti_cgt_armllvm_3.2.2.LTS_linux-x64_installer.bin
    - apt-get install -y libtinfo5
  script:
    - make
  artifacts:
    name: "PocketBeagle2-MSMP0-Firmware"
    paths:
      - pcu_pocketbeagle2.*
