stages:
  - build
  - release

build-job:
  image: $CI_REGISTRY/jkridner/debian-build
  tags: ["docker-amd64"]
  stage: build
  before_script:
    - wget https://dr-download.ti.com/software-development/ide-configuration-compiler-or-debugger/MD-ayxs93eZNN/3.2.2.LTS/ti_cgt_armllvm_3.2.2.LTS_linux-x64_installer.bin
    - chmod +x ./ti_cgt_armllvm_3.2.2.LTS_linux-x64_installer.bin
    - ./ti_cgt_armllvm_3.2.2.LTS_linux-x64_installer.bin
    - apt-get install -y libtinfo5
  script:
    - make
  artifacts:
    name: "PocketBeagle2-MSMP0-Firmware"
    paths:
      - pcu_pocketbeagle2.*

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    URL: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/mspm0_adc_eeprom/${CI_COMMIT_TAG}/mspm0_adc_eeprom.txt
  before_script:
    - apk add --no-cache curl
  script:
    - echo "running release_job for $CI_COMMIT_TAG"
    - 'curl --fail-with-body --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file pcu_pocketbeagle2.txt ${URL}'
  release:
    tag_name: $CI_COMMIT_TAG
    name: 'PocketBeagle2 MSPM0 ADC EEPROM $CI_COMMIT_TAG'
    description: 'PocketBeagle2 MSPM0 ADC EEPROM $CI_COMMIT_TAG stable firmware'
    assets:
      links:
        - name: 'MPSM0 ADC EEPROM'
          url: '${URL}'
          link_type: 'package'
